In [58]:
import pandas as pd
salaries = [45000,52000,0,61000,58000,72000,67000,69000]
deparments = ["developer","marketing","hr", "sales","sales","finance","support","support"]
salary_series = pd.Series(salaries, index = deparments , name = "Salary")
salary_series

developer    45000
marketing    52000
hr               0
sales        61000
sales        58000
finance      72000
support      67000
support      69000
Name: Salary, dtype: int64

In [62]:

salary_series.reset_index()
# type(salary_series.reset_index())
# print(salary_series)

       index  Salary
0  developer   45000
1  marketing   52000
2         hr       0
3      sales   61000
4      sales   58000
5    finance   72000
6    support   67000
7    support   69000

In [ ]:
salary_series.reset_index(drop = True)

0    45000
1    52000
2        0
3    61000
4    58000
5    72000
6    67000
7    69000
Name: Salary, dtype: int64

   level_0      index  Salary
0        0  developer   45000
1        1  marketing   52000
2        2         hr       0
3        3      sales   61000
4        4      sales   58000
5        5    finance   72000
6        6    support   67000
7        7    support   69000